on: [ push, pull_request ]
name: Continuous Integration

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Display Rust and Cargo versions
        run: |
          rustc -Vv
          cargo -V

      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions-rs/cargo@v1
        with:
          command: test